package com.boardgames.gui;

import javax.swing.*;
import java.awt.*;

public class BoardgameExpertGUI {
  private JLabel topLabel;
  private JButton bottomButton;
  private JPanel mainPanel;
  private JPanel outerPanel;
  private JPanel buttonPanel;
  private JPanel labelPanel;
  private JPanel contentPanel;

  public void createAndShow() {
    JFrame frame = new JFrame("Boardgame Expert");
    frame.setContentPane(this.outerPanel);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setLocationRelativeTo(null); // Center in screen
    frame.setVisible(true);
  }

  public JPanel getContentPanel() {
    return contentPanel;
  }

  public JButton getBottomButton() {
    return bottomButton;
  }

  public void setTextToTopLabel(String text) {
    topLabel.setText(text);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    outerPanel = new JPanel();
    outerPanel.setLayout(new BorderLayout(0, 0));
    outerPanel.setMaximumSize(new Dimension(480, 250));
    outerPanel.setMinimumSize(new Dimension(480, 250));
    outerPanel.setPreferredSize(new Dimension(480, 250));
    outerPanel.setVerifyInputWhenFocusTarget(false);
    mainPanel = new JPanel();
    mainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
    mainPanel.setMaximumSize(new Dimension(480, 250));
    mainPanel.setMinimumSize(new Dimension(480, 250));
    mainPanel.setPreferredSize(new Dimension(480, 250));
    outerPanel.add(mainPanel, BorderLayout.CENTER);
    labelPanel = new JPanel();
    labelPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 30));
    labelPanel.setMaximumSize(new Dimension(-1, -1));
    labelPanel.setMinimumSize(new Dimension(450, -1));
    labelPanel.setPreferredSize(new Dimension(450, 77));
    mainPanel.add(labelPanel);
    topLabel = new JLabel();
    topLabel.setHorizontalAlignment(2);
    topLabel.setHorizontalTextPosition(2);
    topLabel.setText("question");
    topLabel.setVerticalAlignment(0);
    labelPanel.add(topLabel);
    contentPanel = new JPanel();
    contentPanel.setLayout(new BorderLayout(0, 0));
    mainPanel.add(contentPanel);
    buttonPanel = new JPanel();
    buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 0, 20));
    buttonPanel.setMaximumSize(new Dimension(-1, -1));
    buttonPanel.setMinimumSize(new Dimension(430, -1));
    buttonPanel.setPreferredSize(new Dimension(430, 70));
    mainPanel.add(buttonPanel);
    bottomButton = new JButton();
    bottomButton.setText("Next");
    buttonPanel.add(bottomButton);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return outerPanel;
  }

}
