package com.boardgames.gui;

import com.boardgames.AnswerHandle;

import javax.swing.*;
import java.awt.*;

public class CheckboxPanel {
  private JPanel checkboxButtonGroup;
  private JCheckBox firstAnswerCheckbox;
  private JCheckBox secondAnswerCheckbox;

  public CheckboxPanel(AnswerHandle answerHandle1, AnswerHandle answerHandle2) {
    firstAnswerCheckbox.setText(answerHandle1.getAnswerString());
    firstAnswerCheckbox.addActionListener(e -> answerHandle1.toggleAnswer());
    secondAnswerCheckbox.setText(answerHandle2.getAnswerString());
    secondAnswerCheckbox.addActionListener(e -> answerHandle2.toggleAnswer());
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    checkboxButtonGroup = new JPanel();
    checkboxButtonGroup.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
    checkboxButtonGroup.setMaximumSize(new Dimension(-1, -1));
    checkboxButtonGroup.setMinimumSize(new Dimension(430, -1));
    checkboxButtonGroup.setPreferredSize(new Dimension(430, 100));
    firstAnswerCheckbox = new JCheckBox();
    firstAnswerCheckbox.setHorizontalAlignment(2);
    firstAnswerCheckbox.setHorizontalTextPosition(11);
    firstAnswerCheckbox.setMargin(new Insets(5, 2, 5, 200));
    firstAnswerCheckbox.setText("");
    checkboxButtonGroup.add(firstAnswerCheckbox);
    secondAnswerCheckbox = new JCheckBox();
    secondAnswerCheckbox.setMargin(new Insets(5, 2, 5, 200));
    secondAnswerCheckbox.setText("");
    checkboxButtonGroup.add(secondAnswerCheckbox);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return checkboxButtonGroup;
  }

}
