package com.boardgames.gui;

import com.boardgames.AnswerHandle;

import javax.swing.*;
import java.awt.*;

public class RadioButtonPanel {
  private JRadioButton firstAnswerRadioButton;
  private JRadioButton secondAnswerRadioButton;
  private JPanel radioButtonGroup;

  public RadioButtonPanel(AnswerHandle answerHandle1, AnswerHandle answerHandle2) {
    firstAnswerRadioButton.setText(answerHandle1.getAnswerString());
    firstAnswerRadioButton.addActionListener(e -> answerHandle1.toggleAnswer());
    secondAnswerRadioButton.setText(answerHandle2.getAnswerString());
    secondAnswerRadioButton.addActionListener(e -> answerHandle2.toggleAnswer());
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    radioButtonGroup = new JPanel();
    radioButtonGroup.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
    radioButtonGroup.setMaximumSize(new Dimension(-1, -1));
    radioButtonGroup.setMinimumSize(new Dimension(430, -1));
    radioButtonGroup.setPreferredSize(new Dimension(430, 100));
    firstAnswerRadioButton = new JRadioButton();
    firstAnswerRadioButton.setHorizontalAlignment(2);
    firstAnswerRadioButton.setHorizontalTextPosition(11);
    firstAnswerRadioButton.setLabel("");
    firstAnswerRadioButton.setMargin(new Insets(5, 2, 5, 200));
    firstAnswerRadioButton.setSelected(false);
    radioButtonGroup.add(firstAnswerRadioButton);
    secondAnswerRadioButton = new JRadioButton();
    secondAnswerRadioButton.setLabel("");
    secondAnswerRadioButton.setMargin(new Insets(5, 2, 5, 200));
    radioButtonGroup.add(secondAnswerRadioButton);
    ButtonGroup buttonGroup;
    buttonGroup = new ButtonGroup();
    buttonGroup.add(secondAnswerRadioButton);
    buttonGroup.add(firstAnswerRadioButton);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return radioButtonGroup;
  }

}
