package com.boardgames.gui;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class ResultPanel {

  private JPanel resultPanel;
  private JLabel resultLabel;

  private List<String> resultList = new ArrayList<>();

  public void addToResultList(String text) {
    resultList.add(text);
    String joined = String.join(", ", resultList);
    resultLabel.setText(joined);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    resultPanel = new JPanel();
    resultPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 2, 0));
    resultPanel.setMaximumSize(new Dimension(-1, -1));
    resultPanel.setMinimumSize(new Dimension(430, -1));
    resultPanel.setPreferredSize(new Dimension(430, 100));
    resultLabel = new JLabel();
    resultLabel.setHorizontalAlignment(2);
    resultLabel.setHorizontalTextPosition(11);
    resultLabel.setMinimumSize(new Dimension(300, 29));
    resultLabel.setPreferredSize(new Dimension(300, 29));
    resultLabel.setText("dummy");
    resultPanel.add(resultLabel);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return resultPanel;
  }

}
