package com.boardgames.gui;

import javax.swing.*;
import java.awt.*;

public class WelcomePanel {
  private JPanel welcomePanel;

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    welcomePanel = new JPanel();
    welcomePanel.setLayout(new FlowLayout(FlowLayout.LEFT, 2, 0));
    welcomePanel.setMaximumSize(new Dimension(-1, -1));
    welcomePanel.setMinimumSize(new Dimension(430, -1));
    welcomePanel.setPreferredSize(new Dimension(430, 100));
    final JLabel label1 = new JLabel();
    label1.setHorizontalAlignment(2);
    label1.setHorizontalTextPosition(11);
    label1.setMinimumSize(new Dimension(300, 29));
    label1.setPreferredSize(new Dimension(300, 29));
    label1.setText("Ewa Fengler, 132219");
    welcomePanel.add(label1);
    final JLabel label2 = new JLabel();
    label2.setMinimumSize(new Dimension(300, 29));
    label2.setPreferredSize(new Dimension(300, 29));
    label2.setText("Krzysztof Michalak, 132281");
    welcomePanel.add(label2);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return welcomePanel;
  }

}
